# GitHub Actions docs
# https://help.github.com/en/articles/about-github-actions
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          check-latest: true
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn run build --prod
      - name: Test
        run: yarn test --code-coverage --watch false --progress false
      # - name: E2E
      #   run: npm run e2e --configuration=ci
