name: main

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          check-latest: true

      - uses: actions/cache@v2
        id: yarn-and-build-cache
        with:
          path: |
            ~/.cache/Cypress
            build
            node_modules
          key: ${{ runner.os }}-node_modules-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-build-

      - name: Install dependencies
        run: yarn install --ignore-engines

      - name: Build
        run: yarn run build --configuration production

      - name: Test
        run: yarn test --code-coverage --watch false

      - name: e2e
        uses: cypress-io/github-action@v2
        with:
          install: false
          cache-key: ${{ runner.os }}-node_modules-build-${{ hashFiles('**/yarn.lock') }}
          start: yarn start --prod
          wait-on: "http://localhost:4200/"
          wait-on-timeout: 120
          config-file: cypress.json
        env:
          CYPRESS_baseUrl: http://localhost:4200/

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos
