name: main

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"

      - uses: actions/cache@v3
        id: yarn-and-build-cache
        with:
          path: |
            ~/.cache/Cypress
            build
            node_modules
          key: ${{ runner.os }}-node_modules-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-build-

      - name: Install dependencies
        run: yarn install --ignore-engines

      - name: Build
        run: yarn run build --configuration production

      - name: Run lint check
        run: yarn run lint

      - name: Run format check
        run: yarn run format:check

      - name: Test
        run: yarn test --code-coverage --watch false

      - name: e2e
        uses: cypress-io/github-action@v2
        with:
          install: false
          cache-key: ${{ runner.os }}-node_modules-build-${{ hashFiles('**/yarn.lock') }}
          start: yarn start --configuration production
          wait-on: "http://[::1]:4200"
          config-file: cypress.config.ts

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos
